### ISSUE TITLE
Fringe scaling exception when OTA is extremely saturated

### ISSUE THREAD

**Issue by agopu** [WIYN-ODI/QuickReduce#12]
Heidi/Wilson reported QR failures with certain input images within PPA. Mike & I looked into this. We discovered that persistency part of the job finishes despite the job status indicating it's still going on. QR was indeed erroring out of processing the 1st image. 

We tried removing the 1st image in case it had a bad FITS file, and discovered the same error cropped up with another image.  We suspect this has to do an extremely saturated field in the top left OTA - see ImageX thumbnail view screenshot of a collection of the raw images from that PROPID, in particular watch OTA 56/top left - which in turn is causing QR to error out with this error:

![image](https://user-images.githubusercontent.com/2206370/51864661-57be8d00-2312-11e9-8592-1423c0f7de39.png)

```2019-01-11 17:44:54,736 Process-2:83 20190102T195810.2 - OTA56.SCI INFO     Starting work on OTA 56 of 20190102T195810.2 ...
2019-01-11 17:45:36,905 Process-2:83 parallel_collectcells CRITICAL 

=========== EXCEPTION ==============
etype: <type 'exceptions.IndexError'>
error: too many indices for array
stackpos: <traceback object at 0x7fa044530ea8>
---

Traceback (most recent call last):
  File "/usr/local/quickreduce/production//podi_collectcells.py", line 1818, in parallel_collect_reduce_ota
    data_products = collect_reduce_ota(filename, options=options)
  File "/usr/local/quickreduce/production//podi_collectcells.py", line 1244, in collect_reduce_ota
    good_scalings = three_sigma_clip(fringe_scaling[:,6], [0, 1e9])
IndexError: too many indices for array

--- end
```

We could execute the job without selecting fringe correction but odds are the PI wants fringe correction to be applied.  Mike also found that there's a QR commandline argument which could be used to bypass this issue... by calling collectcells with an additional argument of "-skipota=56".  However, ideally QR would handle the input data as-is without erroring out so I am filing this bug report (per our IM conversation.) Thanks for looking into this!

**Comment by rkotulla** [comment]
I've just pushed commit https://github.com/WIYN-ODI/QuickReduce/commit/9007b4331f9340f16185cb2024ff173243c877f8 - by default, OTAs used for guiding are now excluded when calculating the global fringe scaling factor. In theory that should fix this problem. I've tried this with some frames (e.g. o20190826T015434.3) and seems to do the trick. If you can dig out what frames were causing this problem and re-test with this latest version that would be awesome.

**Comment by agopu** [comment]
Thanks @rkotulla - we will test this out asap.

**Comment by youngmd** [comment]
Took a while to track down one of the original observations.  20190102T195810.2 (from job 7878) was the one producing the above error.  Re-ran with the updated QR and made sure fringe correction was applied.  Image was processed successfully with no errors and output was ingested, as seen here:  https://portal.odi.iu.edu/exposure/exobj?id=98653
